from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from items import views
from items.views import PostViewSet, api_root
from rest_framework import renderers
#from items.views import UserViewSet

# including an autogenerated schema view

#"in the urls.py file we bind our ViewSet classes into a set of concrete views

item_list = PostViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
item_detail = PostViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
#user_list = UserViewSet.as_view({
#    'get': 'list'
#})
#user_detail = UserViewSet.as_view({
    #'get': 'retrieve'
#})


# API endpoints
urlpatterns = format_suffix_patterns([
    url(r'^api/$', api_root),
    url(r'^items/$', item_list, name='item-list'),
    url(r'^items/(?P<pk>[0-9]+)/$', item_detail, name='item-detail'),
#    url(r'^users/$', user_list, name='user-list'),
#    url(r'^users/(?P<pk>[0-9]+)/$', user_detail, name='user-detail'),
])

# Login and logout views for the browsable API
urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]
